### ISSUE TITLE
Publish v1.2 to Packagist?

### ISSUE THREAD

**Issue by vpyatnitskiy** [kesar/HTMLawed#18]
Hi,

I see you've already [tagged](https://github.com/kesar/HTMLawed/tree/1.2) the [version 1.2](https://github.com/kesar/HTMLawed/releases/tag/1.2) here.

Can you publish it to Packagist?

The latest version available [there](https://packagist.org/packages/htmlawed/htmlawed) is 1.1.22, which is not compatible with PHP 7.2+ ([`create_function` is deprecated](https://www.php.net/manual/en/function.create-function.php) in 7.2.0).
I had to resort to `dev-master` to update.

(This might be related to `"version":"1.1.22"` written in `composer.json`, which is now removed, but 1.2 was tagged before the removal...)

Thank you!

**Comment by lucc** [comment]
@kesar are you still maintaining this repository or the packagist version of htmlawed?

**Comment by vpyatnitskiy** [comment]
@lucc I wouldn't bet on it. The last activity here was in 2018, and this issue went without reply for almost 1.5 years. Just give up, look for a different package (I did) or make your own fork.

Sorry for intruding ― I received a notification and figured it's worth to chime in.

**Comment by lucc** [comment]
@vpyatnitskiy which alternative are you using?

**Comment by kesar** [comment]
sorry I dont have too much time to keep it maintained. If any of you want to help with that I am happy adding you as admins to the repo

**Comment by vpyatnitskiy** [comment]
@lucc I looked at my code, and it turned out that I skipped composer and just downloaded [the original htmLawed](http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/) and committed it as part of my project code. Sorry for the misleading remark.

@kesar I'll pass, don't have much time to maintain a public package either. But thanks for the offer.

**Comment by KorvinSzanto** [comment]
@kesar I'd be happy to help manage this repo if you still need it. In order to do what's asked for here I'd need access in packagist more than in github.

What you need to do is hit the refresh button here: https://packagist.org/packages/htmlawed/htmlawed Like I said I'd be happy to help if you give me access.

**Comment by kesar** [comment]
@KorvinSzanto I added you there if this is your packagist acc ( https://packagist.org/users/KorvinSzanto/ ) :)

**Comment by KorvinSzanto** [comment]
The v1.2 release isn't happy due to some conflicts with the composer.json in the tag. Rather than removing and recreating the tag I've opted to instead tag `1.2.4.1` and `1.2.6` (the latest version) for folks using composer 👍
