### ISSUE TITLE
Missing tag for 1.1.20

### ISSUE THREAD

**Issue by remicollet** [kesar/HTMLawed#8]
It seems 1.1.20 have been imported on July 2nd, but not tagged.

So packagist only list 1.1.19
https://packagist.org/packages/htmlawed/htmlawed

**Comment by Synchro** [comment]
Please?

**Comment by mrclay** [comment]
Current tag should be 1.1.22.

**Comment by mrclay** [comment]
```
git tag 1.1.20 1df80388ef46f50306709c73df0f09c2643872fa
git tag 1.1.22 b270453ba016ee4c6dae585f047d1e4f3cc456a1
git push --tags
```

**Comment by kesar** [comment]
sorry for the delay guys, 👍  done
